services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 2s
      retries: 5
      start_period: 5s
    develop:
      watch:
        - path: ./api/
          target: /app/
          action: sync
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_KEY=${JWT_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
  postgres:
    image: postgres:16-alpine3.22
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'select * from isready;'",
        ]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_PASSWORD=${PG_PASSWORD}
      - TZ=Africa/Casablanca
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d:ro"
      - "pg_data:/var/lib/postgresql/data"
      
    expose:
      - 5432
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pg_data: