services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 2s
      retries: 5
      start_period: 5s
    develop:
      watch:
        - path: ./api/
          target: /app/
          action: sync
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_KEY=${JWT_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
  postgres:
    image: postgres:16-alpine3.22
    healthcheck:
      test: ["CMD-SHELL", "psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'select * from isready;'"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_PASSWORD=${PG_PASSWORD}
      - TZ=Africa/Casablanca
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d:ro"
    expose:
      - 5432